/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AmortisementLigne } from './models/amortisement-ligne';
export type { Assurance } from './models/assurance';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { CategorieCredit } from './models/categorie-credit';
export type { CategorieDto } from './models/categorie-dto';
export type { DeblocageLigne } from './models/deblocage-ligne';
export type { Frais } from './models/frais';
export type { FrAss } from './models/fr-ass';
export type { GrantedAuthority } from './models/granted-authority';
export type { HistoriqueTauxUsure } from './models/historique-taux-usure';
export type { Notification } from './models/notification';
export type { RegistrationRequest } from './models/registration-request';
export type { Simulation } from './models/simulation';
export type { SimulationDtoRequest } from './models/simulation-dto-request';
export type { SimulationDtoResponse } from './models/simulation-dto-response';
export type { SimulationRequestGlobal } from './models/simulation-request-global';
export type { TauxUsure } from './models/taux-usure';
export type { TauxUsureDto } from './models/taux-usure-dto';
export type { TauxUsureStatistiqueDto } from './models/taux-usure-statistique-dto';
export type { User } from './models/user';
