/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimulationDtoRequest } from '../../models/simulation-dto-request';
import { SimulationDtoResponse } from '../../models/simulation-dto-response';

export interface CalculerTeg$Params {
      body: SimulationDtoRequest
}

export function calculerTeg(http: HttpClient, rootUrl: string, params: CalculerTeg$Params, context?: HttpContext): Observable<StrictHttpResponse<SimulationDtoResponse>> {
  const rb = new RequestBuilder(rootUrl, calculerTeg.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SimulationDtoResponse>;
    })
  );
}

calculerTeg.PATH = '/api/simulation/calculer';
