/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Simulation } from '../../models/simulation';
import { SimulationDtoRequest } from '../../models/simulation-dto-request';

export interface MettreAjour$Params {
  idSimulation: number;
      body: SimulationDtoRequest
}

export function mettreAjour(http: HttpClient, rootUrl: string, params: MettreAjour$Params, context?: HttpContext): Observable<StrictHttpResponse<Simulation>> {
  const rb = new RequestBuilder(rootUrl, mettreAjour.PATH, 'put');
  if (params) {
    rb.path('idSimulation', params.idSimulation, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Simulation>;
    })
  );
}

mettreAjour.PATH = '/api/simulation/mettrejour/{idSimulation}';
