/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Simulation } from '../../models/simulation';
import { SimulationRequestGlobal } from '../../models/simulation-request-global';

export interface SaveSimulation$Params {
  email: string;
      body: SimulationRequestGlobal
}

export function saveSimulation(http: HttpClient, rootUrl: string, params: SaveSimulation$Params, context?: HttpContext): Observable<StrictHttpResponse<Simulation>> {
  const rb = new RequestBuilder(rootUrl, saveSimulation.PATH, 'post');
  if (params) {
    rb.path('email', params.email, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Simulation>;
    })
  );
}

saveSimulation.PATH = '/api/simulation/save/{email}';
