/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FrAss } from '../../models/fr-ass';

export interface ChampCategorie$Params {
  id: number;
}

export function champCategorie(http: HttpClient, rootUrl: string, params: ChampCategorie$Params, context?: HttpContext): Observable<StrictHttpResponse<FrAss>> {
  const rb = new RequestBuilder(rootUrl, champCategorie.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FrAss>;
    })
  );
}

champCategorie.PATH = '/api/categorieCredit/listDesChamp/{id}';
