/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmortisementLigne {
  assurance?: number;
  capitalRestant?: number;
  echeanceTotale?: number;
  interet?: number;
  numero?: number;
  principal?: number;
}
