/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface AuthenticationResponse {
  refreshToken?: string;
  token?: string;
  user?: User;
  userList?: Array<User>;
}
