/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategorieCredit {
  assurances?: Array<string>;
  creationDate?: string;
  description?: string;
  fraisObligatoire?: Array<string>;
  id?: number;
  lastModifyDate?: string;
  nomCategorie?: string;
}
