/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategorieDto {
  assurances?: Array<string>;
  description?: string;
  fraisObligatoire?: Array<string>;
  id?: number;
  nomCategorie?: string;
}
