/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistoriqueTauxUsure {
  ancienSeuil?: number;
  ancienTauxUsure?: number;
  ancienneAnnee?: number;
  dateModification?: string;
  id?: number;
  nouveauSeuil?: number;
  nouveauTauxUsure?: number;
  nouvelleAnnee?: number;
  tauxUsureId?: number;
  typeChangement?: string;
}
