/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Simulation } from '../models/simulation';
export interface Notification {
  alerte?: boolean;
  annee?: number;
  creationDate?: string;
  dateNotification?: string;
  id?: number;
  lastModifyDate?: string;
  message?: string;
  simulation?: Simulation;
}
