/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmortisementLigne } from '../models/amortisement-ligne';
import { Assurance } from '../models/assurance';
import { CategorieCredit } from '../models/categorie-credit';
import { DeblocageLigne } from '../models/deblocage-ligne';
import { Frais } from '../models/frais';
export interface Simulation {
  assuranceJson?: Array<Assurance>;
  categorieCredit?: CategorieCredit;
  coutTotal?: number;
  creationDate?: string;
  dateDebut?: string;
  datePremiereEcheance?: string;
  datefin?: string;
  duree?: number;
  echeance?: number;
  fraisJson?: Array<Frais>;
  frequence?: 'MENSUELLE' | 'ANNUELLE' | 'TRIMESTRIALITE';
  id?: number;
  lastModifyDate?: string;
  montant?: number;
  tableauAmortisement?: Array<AmortisementLigne>;
  tableauDeblocages?: Array<DeblocageLigne>;
  tauxNominal?: number;
  teg?: number;
  typeEmprunteur?: 'Particulier' | 'PME' | 'GrandeEntreprise';
}
