/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmortisementLigne } from '../models/amortisement-ligne';
export interface SimulationDtoResponse {
  echeance?: number;
  tableauAmortissement?: Array<AmortisementLigne>;
  tegAnnuel?: number;
}
