/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategorieCredit } from '../models/categorie-credit';
export interface TauxUsure {
  annee?: number;
  categorieCredit?: CategorieCredit;
  creationDate?: string;
  id?: number;
  lastModifyDate?: string;
  seuil?: number;
  tauxTEGMoyen?: number;
  tauxUsure?: number;
  typeEmprunteur?: 'Particulier' | 'PME' | 'GrandeEntreprise';
}
