/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TauxUsureDto {
  annee?: number;
  categorieId?: number;
  seuil?: number;
  typeEprunteur?: 'Particulier' | 'PME' | 'GrandeEntreprise';
}
