/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TauxUsure } from '../../models/taux-usure';

export interface GetListeByCategorieId$Params {
  idCategorie: number;
}

export function getListeByCategorieId(http: HttpClient, rootUrl: string, params: GetListeByCategorieId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TauxUsure>>> {
  const rb = new RequestBuilder(rootUrl, getListeByCategorieId.PATH, 'get');
  if (params) {
    rb.path('idCategorie', params.idCategorie, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TauxUsure>>;
    })
  );
}

getListeByCategorieId.PATH = '/api/tauxUsure/listeParCategorie/{idCategorie}';
