/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TauxUsure } from '../../models/taux-usure';
import { TauxUsureDto } from '../../models/taux-usure-dto';

export interface UpdateTauxUsure$Params {
  id: number;
      body: TauxUsureDto
}

export function updateTauxUsure(http: HttpClient, rootUrl: string, params: UpdateTauxUsure$Params, context?: HttpContext): Observable<StrictHttpResponse<TauxUsure>> {
  const rb = new RequestBuilder(rootUrl, updateTauxUsure.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TauxUsure>;
    })
  );
}

updateTauxUsure.PATH = '/api/tauxUsure/update/{id}';
