/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { afficherNotifSimulation } from '../fn/notification-controller/afficher-notif-simulation';
import { AfficherNotifSimulation$Params } from '../fn/notification-controller/afficher-notif-simulation';
import { Notification } from '../models/notification';

@Injectable({ providedIn: 'root' })
export class NotificationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `afficherNotifSimulation()` */
  static readonly AfficherNotifSimulationPath = '/api/notification/afficherNot/{idSimulation}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `afficherNotifSimulation()` instead.
   *
   * This method doesn't expect any request body.
   */
  afficherNotifSimulation$Response(params: AfficherNotifSimulation$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Notification>>> {
    return afficherNotifSimulation(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `afficherNotifSimulation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  afficherNotifSimulation(params: AfficherNotifSimulation$Params, context?: HttpContext): Observable<Array<Notification>> {
    return this.afficherNotifSimulation$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Notification>>): Array<Notification> => r.body)
    );
  }

}
