/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { savePhotos } from '../fn/photos-controller/save-photos';
import { SavePhotos$Params } from '../fn/photos-controller/save-photos';

@Injectable({ providedIn: 'root' })
export class PhotosControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `savePhotos()` */
  static readonly SavePhotosPath = '/auth/photos/{email}/{title}/{context}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `savePhotos()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  savePhotos$Response(params: SavePhotos$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return savePhotos(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `savePhotos$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  savePhotos(params: SavePhotos$Params, context?: HttpContext): Observable<{
}> {
    return this.savePhotos$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
